version: '3.7'

volumes:
  gems:

services:
  postgres:
    image: postgres:11.8-alpine
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web:
    build: .
    depends_on:
      - postgres
    ports:
      - 3000:3000
    volumes:
      - gems:/usr/local/bundle
      - .:/opt/app:cached
    environment:
      DATABASE_URL: postgres://pguser:postgres@postgres/app_development
      TIME_ZONE: 'Brasilia'
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
